[env]
TERM = "xterm-256color"

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.9

[window.padding]
x = 25
y = 20

[font]
size = 12

[font.bold]
family = "FiraCode Nerd Font"
style = "Heavy"

[font.italic]
family = "FiraCode Nerd Font"
style = "Medium Italic"

[font.normal]
family = "FiraCode Nerd Font"
style = "Medium"

[colors]
[colors.primary]
background= "#2e3440"
foreground= "#d8dee9"
dim_foreground= "#a5abb6"
[colors.cursor]
    text= "#2e3440"
    cursor= "#d8dee9"
[colors.vi_mode_cursor]
    text= "#2e3440"
    cursor= "#d8dee9"
[colors.selection]
    text= "#d8dee9"
    background= "#4c566a"
[colors.search]
[colors.search.matches]
      foreground= "#d8dee9"
      background= "#88c0d0"
[colors.normal]
    black= "#3b4252"
    red= "#bf616a"
    green= "#a3be8c"
    yellow= "#ebcb8b"
    blue= "#81a1c1"
    magenta= "#b48ead"
    cyan= "#88c0d0"
    white= "#e5e9f0"
[colors.bright]
    black= "#4c566a"
    red= "#bf616a"
    green= "#a3be8c"
    yellow= "#ebcb8b"
    blue= "#81a1c1"
    magenta= "#b48ead"
    cyan= "#8fbcbb"
    white= "#eceff4"
[colors.dim]
    black= "#373e4d"
    red= "#94545d"
    green= "#809575"
    yellow= "#b29e75"
    blue= "#68809a"
    magenta= "#8c738c"
    cyan=  "#6d96a5"
    white = "#aeb3bb"
